--VERIFICO LOS MODULOS Y SUBMMODULOR
SELECT * FROM CLSA.WEB_MODULOS_NOMBRE--VERIFDICA LOS MODULOS

SELECT * FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=10 or MODULO=12 ORDER BY MODULO--VERIFICA MODULOS Y SUBMODULOS

SELECT * FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=10 ORDER BY SUBMODULO

--Luego de crear un modulo o submodulo se le debe dar los permisos para que se pueda ver
SELECT * FROM CLSA.WEB_MODULOS_USUARIO  WHERE MODULO=10 order by USUARIO 

SELECT * FROM CLSA.WEB_MODULOS_USUARIO  WHERE MODULO=10 and USUARIO='pruebapma' 

--OTORGA ACCESO AL MODULO Y SUBMODULO 
--INSERT INTO CLSA.WEB_MODULOS_USUARIO
--SELECT 'PRUEBAPMA',MODULO, SUBMODULO FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=10
--AND SUBMODULO=6


--INSERT INTO CLSA.WEB_MODULOS_USUARIO
--SELECT 'PRUEBAPMA',MODULO, SUBMODULO FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=4
--AND SUBMODULO=7
