
--PARA CREAR UN NUEVO MODULO EN EL MENÚ ES NECESARIO:
--CREARLO EN LA TABLA  CLSA.WEB_MODULOS_NOMBRE, 
--CREAR LOS SUBMODULOS DE ESTE EN LA TABLA CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS.
-- ASIGNARLO A LOS USUARIOS USANDO EL SCRIPT DEL INSERT QUE OTORGA ACCESO AL MODULO Y SUBMODULO 
-- PARA QUE SE PUEDA VER EN LOS MODULOS SE DEBE HABILITAR EN LA TABLA CLSA.SISTEMAS_MODULO AGREGANDO EL SISTEMA, NUMERO DEL MODULO, EL ORDEN Y S PARA ACTIVARLO.


--TABLA CLSA.SISTEMAS_MODULO
SELECT * 
FROM CLSA.SISTEMAS_MODULO
WHERE IDSISTEMA = 'WMS' order by ORDEN

--VERIFICO LOS MODULOS Y SUBMMODULOR

SELECT * FROM CLSA.WEB_MODULOS_NOMBRE--VERIFDICA LOS MODULOS.

SELECT * 
FROM CLSA.WEB_MODULOS_NOMBRE
WHERE MODULO IN ('4', '3', '13', '12', '10');


SELECT * FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS WHERE MODULO IN ('4', '3', '13', '12', '10')  ORDER BY MODULO--VERIFICA MODULOS Y SUBMODULOS



SELECT * FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=4 ORDER BY SUBMODULO

SELECT * FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=12 ORDER BY SUBMODULO



--SUBMODULOS
SELECT * FROM CLSA.WEB_MODULOS_USUARIO  WHERE USUARIO = 'gladpavo' order by MODULO

SELECT * FROM CLSA.WEB_MODULOS_USUARIO  WHERE MODULO=10 order by USUARIO 

SELECT * FROM CLSA.WEB_MODULOS_USUARIO AS wm WHERE wm.USUARIO = 'pruebapma' AND wm.MODULO IN (3,10,12,13)  order by MODULO

SELECT * FROM CLSA.WEB_MODULOS_USUARIO  WHERE USUARIO = 'pruebapma' order by MODULO

--MODIFICA LOS NOMBRES DE LOS SUBMODULOS

UPDATE CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS
SET DESCRIPCION = 'Detalles de Transacciones Verificadas'
WHERE MODULO = 12 AND SUBMODULO = 2;

--Luego de crear un modulo o submodulo se le debe dar los permisos para que se pueda ver

--OTORGA ACCESO AL MODULO Y SUBMODULO 

INSERT INTO CLSA.WEB_MODULOS_USUARIO
SELECT 'PRUEBAPMA',MODULO, SUBMODULO FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=10
AND SUBMODULO=8


INSERT INTO CLSA.WEB_MODULOS_USUARIO
SELECT 'PRUEBAPMA',MODULO, SUBMODULO FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=13
AND SUBMODULO=1

INSERT INTO CLSA.WEB_MODULOS_USUARIO
SELECT 'PRUEBAPMA',MODULO, SUBMODULO FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=4
AND SUBMODULO=7

--ELIMINA LOS PERMISOS

DELETE FROM CLSA.WEB_MODULOS_USUARIO
WHERE USUARIO = 'PRUEBAPMA'
  AND MODULO = 4
  AND SUBMODULO = 7;



SELECT * FROM CLSA.WEB_MODULOS_NOMBRE_SUBMODULOS where MODULO=3