/*
				select --top 20 
				ROW_NUMBER() OVER(ORDER BY T1.FECHA_FACTURA DESC) AS ITEM
				--, T1.DOCUMENTO, T1.ORDEN_TALLER , T1.PEDIDO 
				, CASE WHEN  T1.ORDEN_TALLER IS NOT NULL THEN  T1.ORDEN_TALLER ELSE  T1.DOCUMENTO END DOCUMENTO
				, T1.PEDIDO
				, T1.DESCRIPCION 
				, T1.CLIENTE
				, SUM (CASE WHEN AR.TIPO IN ('T', 'K') THEN PL.CANTIDAD_PEDIDA  ELSE 0 END ) TOTAL_UNIDADES, T1.LINEAS_VERIFICADAS, T1.LINEAS_PREPARADAS
				, T1.ESTADO_PEDIDO , T1.USUARIO 
				, T1.FECHA_FACTURA
				, T1.FECHA_PEDIDO
				, T1.MODULO 
				, T1.CIA
				, T1.NUM_PLACA placa
				--, CLSA.fn_getTieneServicios (T1.PEDIDO ) tiene_servicio
				,(	SELECT CASE WHEN COUNT(PEDIDO) = 0 THEN 'N' ELSE 'S' END  
					FROM BREMEN.PEDIDO_LINEA PL INNER JOIN BREMEN.ARTICULO AR ON  (AR.ARTICULO = PL.ARTICULO )
					WHERE AR.CLASIFICACION_1 = '1040' AND AR.TIPO = 'V'
					AND PL.PEDIDO = T1.PEDIDO
				) as tiene_servicio --added by vg 2024.07.17 02:03 pm
				, T1.SOLICITA
				, T1.ATENDIDO_POR
				, ISNULL(T1.FECHA_FACTURA, FECHA_CREACION_PEDIDO) FECHA
				, T1.ESTADO_VERIFICACION as ESTADO_PREPARACION
				FROM (

*/
					 SELECT 
					 -- Datos de la tabla Pedido					
					 CASE WHEN F.FACTURA IS NOT NULL AND F.TIPO_DOCUMENTO='F' THEN F.FACTURA ELSE P.PEDIDO END AS DOCUMENTO --ADDED BY VG 2024.02.28 12:24 PM
					, OT.ORDEN_TALLER 
					, P.PEDIDO 
					, CASE WHEN p.RUBRO1 IS NULL OR p.RUBRO1 = '' THEN p.EMBARCAR_A ELSE p.RUBRO1 END + ' .... ' + convert(varchar, p.createdate, 22) + ' ' as DESCRIPCION, ISNULL((Select SUM(LineaContada) from CLSA.WMS_CONTROL_ENTREGA CE with(nolock) where ((CE.CONSECUTIVO = p.PEDIDO or CE.CONSECUTIVO = OT.ORDEN_TALLER) AND (CE.BODEGA = p.BODEGA) AND CE.ESTADO <> 'E' ) group by CE.CONSECUTIVO), 0) 
					as LINEAS_PREPARADAS,
					ISNULL((Select SUM(LineaVerificada) from CLSA.WMS_CONTROL_ENTREGA CE with(nolock) where ((CE.CONSECUTIVO = p.PEDIDO or CE.CONSECUTIVO = OT.ORDEN_TALLER) AND (CE.BODEGA = p.BODEGA) AND CE.ESTADO NOT IN ('E','G','A')) group by CE.CONSECUTIVO), 0)
					as LINEAS_VERIFICADAS
					
					 ,ISNULL((Select ESTADO from CLSA.WMS_CONTROL_ENTREGA CE with(nolock) where ((CE.CONSECUTIVO = p.PEDIDO or CE.CONSECUTIVO = OT.ORDEN_TALLER) AND (CE.BODEGA = p.BODEGA) AND CE.ESTADO not in ('P', 'E') ) group by ESTADO ), 0) 
										
					 --end modified--
					, p.embarcar_a as CLIENTE
					, P.Estado ESTADO_PEDIDO
					, p.USUARIO
					, p.fecha_pedido
					, P.RecordDate FECHA_CREACION_PEDIDO
					, F.FECHA FECHA_FACTURA
					, 'P' as MODULO
					, case when (select COUNT(*) from clsa.CLASIFICACION_BODEGAS b with(nolock) WHERE GRUPO_CLASIF<=1 AND b.BODEGA = p.BODEGA)>0 then 'B' 
					  else 'N' end as CIA
					, OT.NUM_PLACA 
					, (select SOLICITA from CLSA.CONTROL_ENTREGA_SOLICITADO X WHERE X.CONSECUTIVO = OT.ORDEN_TALLER ) solicita
					, (SELECT NOMBRE FROM BREMEN.VENDEDOR V WHERE V.VENDEDOR = P.RUBRO2 ) ATENDIDO_POR
					------------------------------
					FROM BREMEN.PEDIDO p with(nolock) 
					LEFT JOIN CLSA.ORDEN_TALLER OT with(nolock) ON  (P.PEDIDO = OT.PEDIDO AND P.BODEGA = OT.BODEGA) 
					LEFT JOIN BREMEN.FACTURA F with(nolock) ON (F.PEDIDO = P.PEDIDO)
					WHERE 0=0  and p.BODEGA = 'B-51' and (F.TIPO_DOCUMENTO = 'F' or (p.tipo_documento='P' and OT.ESTADO IS NOT NULL) ) --ADDED IN 2024.02.05 03:10 PM and CONVERT (VARCHAR (10), P.FECHA_PEDIDO, 112) BETWEEN '20240829'AND'20240829' and p.pedido='P51-10071645' and p.USUARIO='herngonz' Select * from CLSA.WMS_CONTROL_ENTREGA CE with(nolock) where CE.CONSECUTIVO='P51-10071645' /* ) T1
			LEFT JOIN BREMEN.PEDIDO_LINEA PL with(nolock) ON (T1.PEDIDO = PL.PEDIDO )
			LEFT JOIN BREMEN.ARTICULO AR with(nolock) ON (AR.ARTICULO = PL.ARTICULO  AND AR.TIPO <> 'V' ) 
			GROUP BY T1.DOCUMENTO, T1.ORDEN_TALLER , T1.PEDIDO , T1.DESCRIPCION , T1.CLIENTE , T1.ESTADO_PEDIDO, PL.BODEGA, T1.ESTADO_VERIFICACION
			, T1.USUARIO , T1.FECHA_PEDIDO, T1.FECHA_FACTURA , T1.MODULO, T1.CIA, T1.NUM_PLACA , T1.SOLICITA, T1.ATENDIDO_POR, T1.FECHA_CREACION_PEDIDO, T1.LINEAS_PREPARADAS,T1.LINEAS_VERIFICADAS HAVING  T1.LINEAS_PREPARADAS
			< SUM (CASE WHEN AR.TIPO IN ('T', 'K') THEN PL.CANTIDAD_PEDIDA  ELSE 0 END )  
			OR t1.ESTADO_VERIFICACION IN ('G','A')
			ORDER BY  ISNULL(T1.FECHA_FACTURA, FECHA_CREACION_PEDIDO) DESC 
*/
